# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gugu
  password: password000

development:
  <<: *default
  database: test_guru_development
  username: gugu
  password: password000
  host: localhost
  pool: 5

test:
  <<: *default
  database: test_guru_test
  host: localhost
  pool: 5
  username: gugu
  password: password000

production:
  <<: *default
  database: test_guru_production
